### PR TITLE
[202] De-serialize page links in rich text

### PR DESCRIPTION
**Pull request by tm-kn**
Requires back-end - torchbox/wagtail-torchbox#176

https://projects.torchbox.com/projects/tbxcom-redesign/tickets/202

### CODE REVIEW

**Comment by thisoldbear** [comment]
@tm-kn I see that the new component is making use of Hooks.

I'm not sure this is something we want to introduce _just_ yet to the codebase as it may need buy in from the wider front end team (and this would be the only component using it so far), something @helenb can comment on maybe?

Secondly, I'm not sure useState is actually _needed_ here as the value of `props.value` does not change over time in the traditional sense of state (granted, it will change when the value is passed in), so it may be pertinent to use the value immediately in the render, and pass it into a helper to return the html?

However, the HTML parsing (although a necessary evil in this case) is inspired! 😅

Here's an example of the component de-hooked:

```
// Vendor Modules
import React from 'react'
import PropTypes from 'prop-types'
// Utilities
import { pageUrl } from '@utils/urls'

// Could be moved to a util
const parseAnchorsInHtml = html => {
  const el = document.createElement('body')

  el.innerHTML = html

  for (const link of el.querySelectorAll('a[data-page-slug][data-page-type]')) {
    const url = pageUrl({
      type: link.dataset.pageType,
      slug: link.dataset.pageSlug,
      serviceSlug: link.dataset.pageServiceSlug,
    })

    link.href = url

    delete link.dataset.pageType
    delete link.dataset.pageSlug
    delete link.dataset.pageServiceSlug
  }

  return el.innerHTML
}

const RichText = ({ value }) => (
  <div dangerouslySetInnerHTML={{ __html: parseAnchorsInHtml(value) }} />
)

RichText.propTypes = {
  value: PropTypes.string,
}

export default RichText
```

**Comment by tm-kn** [comment]
@thisoldbear  Your example will not work because `document` is unaccessible in NodeJS. We need to analyse the links on the runtime. I did not know we are not supposed to use hooks, can switch to class-based component if you insist.

**Comment by tm-kn** [comment]
@thisoldbear We could actually do it at the build time (preferred) if you could recommend me a library that can accomplish that. :P

**Comment by thisoldbear** [comment]
@tm-kn I tested it locally, and was pretty sure it was working 😉

**Comment by tm-kn** [comment]
@thisoldbear 
Did you test with `gatsby build`? See - https://app.netlify.com/sites/tbx-production/deploys/5cd20376a0b2f200084a5b37

**Comment by thisoldbear** [comment]
@tm-kn Good point regarding Node and `document` 👍 

Maybe better to make `parseAnchorsInHtml()` a method on a class component and update `state.html` on `componentDidMount()` then, so that it's only run at runtime.

Unless @helenb, you're okay with hooks being used?

Sorry to be a bother, but I think consistency across the codebase is important so anyone can pick it up.

**Comment by helenb** [comment]
@thisoldbear  happy to go with your recommendations.

**Comment by tm-kn** [comment]
@thisoldbear done.

**Pull request merged**
