### PR TITLE
Add tracking code provided by Autopilot

### PR DESCRIPTION
**Pull request by Stormheg**
[Autopilot](https://www.autopilothq.com/) is a marketing tool that provides some tracking code for the Torchbox site.

### CODE REVIEW

**Comment by zerolab** [comment]
We already use GTM, could this not be injected via GTM?

**Comment by Stormheg** [comment]
I wasn't aware GTM can do that! Will look into that.

**Comment by zerolab** [comment]
Last I checked there were way too many tracker things. I wonder if we can revise that and cut down to the absolutely necessary 🤔

tl;dr I hate trackers

**Comment by zerolab** [comment]
Closing as this was implemented differently

**Pull request closed without merging**
