### PR TITLE
[204] Add markdown + code highlight support

### PR DESCRIPTION
**Pull request by tm-kn**
https://projects.torchbox.com/projects/tbxcom-redesign/tickets/204

### CODE REVIEW

**Comment by helenb** [comment]
Code looks good to me.

**Comment by zerolab** [comment]
Let's get this live?

**Comment by zerolab** [comment]
heh, a small nitpick now that I've seen it live, the codeblock font-size could be a tad smaller
e.g. https://torchbox.com/blog/apache-solr-search-solr-47/

**Comment by tm-kn** [comment]
Could also add horizontal scroll for mobile.

**Pull request merged**
